### ISSUE TITLE
When cloned, it doesn't display!

### ISSUE THREAD

**Issue by deejinng** [devtofunmi/madewithchakra#1]
The issue is basically with the static/incorrect supabase configuration in the .env.development file.

**Comment by devtofunmi** [comment]
Thanks for opening an issue but I can't  possibly reveal the supabase credentials for the project in the codebase, I suggest you create a new supabase project and use your own credentials.
Thanks so much, I look forward to seeing your contribution.

**Comment by deejinng** [comment]
I should say I'm new to Supabase!

Or where can we talk ?

**Comment by devtofunmi** [comment]
hi, sorry for the late reply, you can chat me up on twitter @codebreak_er

**Comment by deejinng** [comment]
> hi, sorry for the late reply, you can chat me up on twitter @codebreak_er

![Screenshot_20221129-080129.png](https://user-images.githubusercontent.com/107402108/204461026-12410904-4666-4d16-954d-4dee85dfe543.png)

If you're not following back I can't seen any message.

I guess we should forget about it lol

**Comment by devtofunmi** [comment]
hi, sorry for the late reply, what is your twitter handle?

**Comment by deejinng** [comment]
Twitter [@deejinng](https://twitter.com/deejinng)
